# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EasyProcessingTool
                                 A QGIS plugin
 Print Pine Wilt Disease Layout
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-05
        copyright            : (C) 2019 by iGIS Corp.
        email                : idscorea1@naver.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PluginTester class from file PluginTester.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .easy_processing_tool import EasyProcessingTool
    return EasyProcessingTool(iface)
